config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  namespace :admin do
    resources :sellers
    resources :buyers
    resources :categories
    resources :offers
    resources :preferences
    resources :reservations

    root to: "sellers#index"
  end

  # allow to setup devise controllers to override default devise controllers,
  # for details, see in App/controllers/sellers/
  devise_for :sellers, controllers: {
        sessions: 'sellers/sessions',
        registrations: 'sellers/registrations',
        passwords: 'sellers/passwords'
      }

  devise_for :buyers, controllers: {
        sessions: 'buyers/sessions',
        registrations: 'buyers/registrations',
        passwords: 'buyers/passwords'
      }

  # create/update/destroy an offer can be settled only by a seller
  resources :sellers, only: :show do
    resources :offers, except: [:show, :index]
  end

  # show an offer can be only applied by a buyer from homepage
  # by this path, buyer can then make a reservation
  resources :offers, only: [:index, :show] do
    resources :reservations, only: :create
  end

  resources :buyers, only: :show do
    resources :reservations, only: [:index, :destroy, :edit, :update]
    resources :preferences
  end

  # alllow to display its own offers to a seller
  namespace :myadmins do
    resources :offers, only: :index do
      resources :reservations, only: :index
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buyer.rb
class Buyer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :reservations, dependent: :destroy
  has_many :preferences, dependent: :destroy

  validates :first_name, presence:true
  validates :last_name, presence:true
  validates :phone, presence:true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, PhotoUploader

end

app/models/category.rb
class Category < ApplicationRecord

  has_many :preferences
  has_many :offers
  validates :name, presence:true

end

app/models/current_context.rb
class CurrentContext
  attr_reader :seller, :buyer

  def initialize(seller, buyer)
    @seller = seller
    @buyer = buyer
  end
end

app/models/offer.rb
class Offer < ApplicationRecord

  belongs_to :seller
  belongs_to :category
  has_many :reservations, dependent: :destroy

  validates :title, presence:true, length: { minimum: 5 }
  validates :price, presence:true
  validates :date, presence:true
  validates :duration, presence:true
  validates :description, presence:true
  validates :image, presence:true
  validates :quantity, presence:true

  mount_uploader :image, PhotoUploader

end

app/models/preference.rb
class Preference < ApplicationRecord

  belongs_to :buyer
  belongs_to :category

end

app/models/reservation.rb
class Reservation < ApplicationRecord

  belongs_to :buyer
  belongs_to :offer
  has_one :seller, through: :offer

  validates :time, presence:true
  validates :number_of_persons, presence:true

end

app/models/seller.rb
class Seller < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :offers, dependent: :destroy
  has_many :reservations, through: :offers

  validates :name, presence:true
  validates :address, presence:true
  validates :zip_code, presence:true
  validates :city, presence:true
  validates :phone_number, presence:true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController

  before_action :set_buyer, only: [:show, :edit, :update]
  skip_before_action :authenticate_seller!

  def show
    @buyer_avatar = @buyer.avatar || "default-avatar.png"
    # @reservations = Reservation.where(buyer_id: @buyer.id)
    # @offers = @reservations.map { |reservation| reservation.offer}
  end

  def edit
  end

  def update
    @buyer.update(buyer_params)
    redirect_to buyer_path(@buyer)
  end

  private

  def buyer_params
    params.require(:buyer).permit(
      :pseudo,
      :first_name,
      :last_name,
      :phone,
      :avatar
    )
  end

  def set_buyer
    @buyer = Buyer.find(params[:id])
    authorize @buyer
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def update
  end

  def destroy
  end

  def show
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController

  before_action :set_offer, only: [:show, :edit, :update, :destroy]
  before_action :set_seller, only: [:edit, :update, :destroy]
  before_action :params_offer, only: [:create, :update]
  # buyer can see an offer in order to make a reservation
  skip_before_action :authenticate_buyer!, except: :show
  # seller must be "signed in" in order to create,update, destroy an offer
  skip_before_action :authenticate_seller!, only: :show
  layout "sellers", except: :show

  def index
    @offers = policy_scope(Offer)
  end

  def new
    @seller = Seller.find(params[:seller_id])
    @offer = Offer.new
    @categories = Category.all.sort_by{ |category| category.name}
    authorize @offer
  end

  def create
    @seller = Seller.find(params[:seller_id])
    @offer = Offer.new(params_offer)
    @offer.seller = @seller
    # @offer.seller = current_seller
    authorize @offer
    if @offer.save
      redirect_to myadmins_offers_path
    else
      render :new
    end
  end

  def edit
    @seller = Seller.find(params[:seller_id])
  end

  def update
    @offer.update(params_offer)
    redirect_to myadmins_offers_path
  end

  def show
    @reservation = Reservation.new
  end

  def destroy
    @offer.destroy
    redirect_to myadmins_offers_path
  end

  private

  def params_offer
    params.require(:offer).permit(
      :title,
      :price,
      :date,
      :duration,
      :description,
      :quantity,
      :seller_id,
      :category_id,
      :image,
      :image_cache
    )
  end

  def set_offer
    @offer = Offer.find(params[:id])
    authorize @offer
  end

  def set_seller
    @seller = Seller.find(params[:seller_id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

skip_before_action :authenticate_buyer!, only: [:home, :restaurantspace  ]
skip_before_action :authenticate_seller!, only: [:restaurantspace, :home ]

  def home
    @offers = policy_scope(Offer)
    @buyer = current_buyer if buyer_signed_in?
  end

end



#   def home
#     @trips = policy_scope(Trip).where('trips.date > ?', Date.today)
#     @trips = @trips.where(date: params[:date]) if params[:date].present?
#     @trips = @trips.global_search(params[:query]) if params[:query].present?
#   end

#   def page_title
#       "Whikend | Trouvez des partenaires de randonnée!"
#   end

# end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController

  before_action :set_seller, only: [ :edit, :update]
  skip_before_action :authenticate_buyer!

  def index
    @sellers = policy_scope(Seller).order(created_at: :desc)
  end

  def show
    @seller = current_seller
    @seller_avatar = @seller.avatar || "default-avatar.png"
    authorize @seller
  end

  def edit
  end

  def update
    @seller.update(seller_params)
    redirect_to seller_path(@seller)
  end

  private

  def set_seller
    @seller = Seller.find(params[:id])
    authorize @seller
  end

  # def seller_params
  #   params.require(:seller).permit(
  #     :name,
  #     :address,
  #     :zip_code,
  #     :city,
  #     :phone_number,
  #     :avatar
  #   )
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/preferences_helper.rb
module PreferencesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<section class="footers text-center" id="footers-19">
  <div class="container">
    <div class="row justify-content-center align-items-stretch no-gutters splited-columns">
      <div class="col-12 col-sm-4 p-30 p-lg-60">
        <div class="pr-sm-30">
          <h5 class="mb-20">Contactez-nous</h5>

         <% if !buyer_signed_in? %>
            <% if seller_signed_in? %>
              <h5 class="mb-20"><%= link_to "Espace restaurateur", seller_path(current_seller) %></h5>
            <% else %>
              <h5 class="mb-20"><%= link_to "Espace restaurateur", new_seller_session_path(current_seller) %></h5>
            <% end %>
        <% end %>

          <p>Mr Smith</p>
          <p>10 rue des gourmets</p>
          <p>69009 Lyon</p>
        </div>
      </div>
      <!-- <div class="col-12 col-sm-4 p-30 p-lg-60">
        <h5 class="mb-20">Suivez-nous</h5>
          <div class="socials"><a href=""><img src="facebook.svg"/></a><a href=""><img src="images/socials/twitter.svg"/></a><a href=""><img src="images/socials/instagram.svg"/></a><a href=""><img src="img/socials/behance.svg"/></a><a href=""><img src="img/socials/google.svg"/></a>
          </div>
      </div> -->
      <!-- <div class="col-12 col-sm-4 p-30 p-lg-60">
              <div class="pl-sm-30">
                <h5 class="mb-20">Get product updates</h5>
                <form>
                  <div class="row no-gutters form-group">
                    <div class="col-8">
                      <div>
                        <input class="form-control form-control-light form-control-small" type="text" placeholder="Input"/>
                      </div>
                    </div>
                    <div class="col-4">
                      <button class="btn btn-small w-full">Button</button>
                    </div>
                  </div>
                </form>
              </div>
            </div> -->
    </div>
  </div>
</section>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-fixed-top">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <span ><%= image_tag "logo.png", height: 50 %></span>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if buyer_signed_in? %>
      <!-- Links when logged in -->

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
      <div class="dropdown">
        <% buyer_avatar = current_buyer.avatar || "default-avatar.png" %>
          <%= cl_image_tag buyer_avatar, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown", crop: :thumb, gravity: :face, width: 300, height: 300 %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Mon profil", buyer_path(current_buyer) %></li>
          <li><%= link_to "Mes reservations", buyer_reservations_path(current_buyer)%></li>
          <li>
            <%= link_to destroy_buyer_session_path, method: :delete do %>
              <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_buyer_session_path, class: "navbar-wagon-item navbar-wagon-link", style: "color: blue" %>
      <%= link_to "Sign up", new_buyer_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <% if buyer_signed_in? %>
  <!-- Dropdown list appearing on mobile only -->
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Mon profil", buyer_path(current_buyer) %></li>
          <li><%= link_to "Se déconnecter", destroy_buyer_session_path %></li>
        </ul>
      </div>
    </div>

    <% else %>

    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Se connecter", new_buyer_registration_path %></li>
        </ul>
      </div>
    </div>
  <% end %>
</div>