config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  namespace :admin do
    resources :sellers
    resources :buyers
    resources :categories
    resources :offers
    resources :preferences
    resources :reservations

    root to: "sellers#index"
  end

  # allow to setup devise controllers to override default devise controllers,
  # for details, see in App/controllers/sellers/
  devise_for :sellers, controllers: {
        sessions: 'sellers/sessions',
        registrations: 'sellers/registrations',
        passwords: 'sellers/passwords'
      }

  devise_for :buyers, controllers: {
        sessions: 'buyers/sessions',
        registrations: 'buyers/registrations',
        passwords: 'buyers/passwords'
      }

  # create/update/destroy an offer can be settled only by a seller
  resources :sellers, only: :show do
    resources :offers, except: [:show, :index]
  end

  # show an offer can be only applied by a buyer from homepage
  # by this path, buyer can then make a reservation
  resources :offers, only: [:index, :show] do
    resources :reservations, only: :create
  end

  resources :buyers, only: :show do
    resources :reservations, only: [:index, :destroy, :edit, :update]
    resources :preferences
  end

  # alllow to display its own offers to a seller
  namespace :myadmins do
    resources :offers, only: :index do
      resources :reservations, only: :index
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/preference.rb
class Preference < ApplicationRecord

  belongs_to :buyer
  belongs_to :category

end

app/controllers/admin/preferences_controller.rb
module Admin
  class PreferencesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Preference.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Preference.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController

  before_action :set_buyer
  before_action :set_preference, only: [:edit, :destroy]
  before_action :available_preferences, only: [:new, :create]
  skip_before_action :authenticate_seller!

  def index
    @preferences = policy_scope(Preference)
    # select the preferences already choosen by the buyer
    @buyer_selected_preferences = @preferences.where(buyer_id: current_buyer.id)
  end

  def new
    @preference = Preference.new
    authorize @preference
  end

  def create
    @preference = Preference.new(params_preferences)
    @preference.buyer_id = @buyer.id

    authorize @preference
    if @preference.save
      redirect_to buyer_preferences_path
    else
      render :new
    end
  end

  def destroy
    @preference.destroy
    authorize @preference
    redirect_to buyer_preferences_path
  end

  private

  def params_preferences
    params.require(:preference).permit(:buyer_id, :category_id)
  end

  def set_buyer
    @buyer = Buyer.find(params[:buyer_id])
  end

  def set_preference
    @preference = Preference.find(params[:id])
  end

  def available_preferences
    # allow to have a list of category_id of preferences that have been selected/not selected by the buyer
    # list of categories id that can be used to build a preference
    @categories = Category.all
    @list_of_all_category_id = @categories.map { |category| category.id }
    # list of preferences already selected by the buyer
    @preferences = Preference.all
    @buyer_selected_preferences = @preferences.where(buyer_id: current_buyer.id)
    # list of preferences selected by a buyer dispalyed by category_id
    @list_of_selected_category_id = @buyer_selected_preferences.map { |preference| preference.category_id }
    # list of preferences not selected by a buyer displayed by category_id
    @list_of_not_selected_category_id = @list_of_all_category_id - @list_of_selected_category_id
  end

end

app/helpers/preferences_helper.rb
module PreferencesHelper
end

app/views/preferences/index.html.erb
<section class="container">

  <h1>Mes préférences</h1>
  <br>
  <% if @buyer_selected_preferences.empty? %>
    <p><%= "Vous n'avez pas encore défini de préférences de restautants" %></p>
    <%= link_to "créer mes préférences", new_buyer_preference_path(@buyer), {class: "button btn primary"} %>
  <% else %>
    <% @buyer_selected_preferences.each do |preference| %>
      <table>
        <tr>
          <td><%= preference.category.name %></td>
          <td><%= link_to "Supprimer", buyer_preference_path(@buyer, preference), method: :delete %></td>
        </tr>
      </table>
    <% end %>
    <%= link_to "Ajouter des préférences", new_buyer_preference_path(@buyer)  %>
  <% end %>
  <br> <%= link_to "retour", buyer_path(@buyer) %>
</section>

app/views/preferences/new.html.erb
<section class="container">

  <h1>Ajouter des préférences</h1>
  <br>
  <% @list_of_not_selected_category_id.each do |category_id| %>
      <%= Category.find(category_id).name %>
     <% @preference.category_id = category_id %>
      <%= simple_form_for([@buyer, @preference]) do |f| %>
      <%= f.input :category_id , as: :hidden %>

        <%= f.submit "Ajouter", class: "btn btn--primary" %>
      <% end %>

  <% end %>

</section>