config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  namespace :admin do
    resources :sellers
    resources :buyers
    resources :categories
    resources :offers
    resources :preferences
    resources :reservations

    root to: "sellers#index"
  end

  # allow to setup devise controllers to override default devise controllers,
  # for details, see in App/controllers/sellers/
  devise_for :sellers, controllers: {
        sessions: 'sellers/sessions',
        registrations: 'sellers/registrations',
        passwords: 'sellers/passwords'
      }

  devise_for :buyers, controllers: {
        sessions: 'buyers/sessions',
        registrations: 'buyers/registrations',
        passwords: 'buyers/passwords'
      }

  # create/update/destroy an offer can be settled only by a seller
  resources :sellers, only: :show do
    resources :offers, except: [:show, :index]
  end

  # show an offer can be only applied by a buyer from homepage
  # by this path, buyer can then make a reservation
  resources :offers, only: [:index, :show] do
    resources :reservations, only: :create
  end

  resources :buyers, only: :show do
    resources :reservations, only: [:index, :destroy, :edit, :update]
    resources :preferences
  end

  # alllow to display its own offers to a seller
  namespace :myadmins do
    resources :offers, only: :index do
      resources :reservations, only: :index
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/offer.rb
class Offer < ApplicationRecord

  belongs_to :seller
  belongs_to :category
  has_many :reservations, dependent: :destroy

  validates :title, presence:true, length: { minimum: 5 }
  validates :price, presence:true
  validates :date, presence:true
  validates :duration, presence:true
  validates :description, presence:true
  validates :image, presence:true
  validates :quantity, presence:true

  mount_uploader :image, PhotoUploader

end

app/controllers/admin/offers_controller.rb
module Admin
  class OffersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Offer.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Offer.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/myadmins/offers_controller.rb
class Myadmins::OffersController < ApplicationController

  skip_before_action :authenticate_buyer!
  layout "sellers"

  def index
    @offers = policy_scope(Offer).where(seller_id: current_seller.id)
  end

end

app/controllers/myoffers/offers_controller.rb
class Myoffers::OffersController < ApplicationController

  skip_before_action :authenticate_buyer!
  layout "sellers"

  def index
    @offers = policy_scope(Offer).where(seller_id: current_seller.id)
  end

end

app/controllers/offers_controller.rb
class OffersController < ApplicationController

  before_action :set_offer, only: [:show, :edit, :update, :destroy]
  before_action :set_seller, only: [:edit, :update, :destroy]
  before_action :params_offer, only: [:create, :update]
  # buyer can see an offer in order to make a reservation
  skip_before_action :authenticate_buyer!, except: :show
  # seller must be "signed in" in order to create,update, destroy an offer
  skip_before_action :authenticate_seller!, only: :show
  layout "sellers", except: :show

  def index
    @offers = policy_scope(Offer)
  end

  def new
    @seller = Seller.find(params[:seller_id])
    @offer = Offer.new
    @categories = Category.all.sort_by{ |category| category.name}
    authorize @offer
  end

  def create
    @seller = Seller.find(params[:seller_id])
    @offer = Offer.new(params_offer)
    @offer.seller = @seller
    # @offer.seller = current_seller
    authorize @offer
    if @offer.save
      redirect_to myadmins_offers_path
    else
      render :new
    end
  end

  def edit
    @seller = Seller.find(params[:seller_id])
  end

  def update
    @offer.update(params_offer)
    redirect_to myadmins_offers_path
  end

  def show
    @reservation = Reservation.new
  end

  def destroy
    @offer.destroy
    redirect_to myadmins_offers_path
  end

  private

  def params_offer
    params.require(:offer).permit(
      :title,
      :price,
      :date,
      :duration,
      :description,
      :quantity,
      :seller_id,
      :category_id,
      :image,
      :image_cache
    )
  end

  def set_offer
    @offer = Offer.find(params[:id])
    authorize @offer
  end

  def set_seller
    @seller = Seller.find(params[:seller_id])
  end

end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/edit.html.erb
<section class="container">

  <h1>Modifier votre offre</h1>

  <%= simple_form_for [@seller, @offer] do |f| %>
    <%= f.error_notification %>
    <%= f.input :title, label: "Titre de votre promotion", placeholder: "Menu gastro à -30% jusqu'à 21h00 " %>
    <%= f.input :description, label: "Description de votre offre", placeholder: "Précisez les détails et conditions de votre offre " %>
    <%= f.input :date, as: :date %>
    <%= f.input :quantity, label: "Nombre d'offres disponibles", as: :string  %>
    <%= f.input :price, as: :string %>
    <%= f.input :duration, as: :string %>
    <%= f.input :category_id, collection: @categories, label: "Sélectionnez votre catégorie" %>
    <%= f.input :image, label: "Photo de votre promotion", hint: "Une belle photo de votre menu attirera plus de monde" %>
    <%= f.input :image_cache, as: :hidden %>

    <%= link_to "Annuler", seller_path(@seller) %>
    <%= f.submit "Mettre à jour", class: "btn btn--primary" %>
      <p>Créer</p>
  <% end %>

</section>

app/views/offers/index.html.erb
<h1>Offers#index</h1>
<p>Find me in app/views/offers/index.html.erb</p>

app/views/offers/new.html.erb
<div class="container">

<h1>Décrivez votre offre</h1>

  <%= simple_form_for [@seller, @offer] do |f| %>
    <%= f.error_notification %>
    <%= f.input :title, label: "Titre de votre promotion", placeholder: "Menu gastro à -30% jusqu'à 21h00 " %>
    <%= f.input :description, label: "Description de votre offre", placeholder: "Précisez les détails et conditions de votre offre " %>
    <%= f.input :date, as: :date %>
    <%= f.input :quantity, label: "Nombre d'offres disponibles", as: :string  %>
    <%= f.input :price, as: :string %>
    <%= f.input :duration, as: :string %>
    <%= f.input :category_id, collection: @categories, label: "Sélectionnez votre catégorie" %>
    <%= f.input :image, label: "Photo de votre promotion", hint: "Une belle photo de votre menu attirera plus de monde" %>
    <%= f.input :image_cache, as: :hidden %>

    <%= link_to "Annuler", seller_path(@seller) %>
    <%= f.submit "Créer", class: "btn btn--primary" %>
  <% end %>

</div>

app/views/offers/show.html.erb
<section class="container">

<h1>Renseignez votre réservation</h1>

  <%=  simple_form_for [@offer, @reservation] do |f| %>
    <%= f.error_notification %>
    <%= f.input :number_of_persons, collection: 1..5, required: true  %>
    <%= f.input :time, as: :time, required: true %>
    <%= f.input :comment, required: false %>
    <%= f.button :submit, "Valider" %>
  <% end %>

</section>